### ISSUE TITLE
Implement additional meta-data to user accounts.

### ISSUE THREAD

**Issue by Blakeinstein** [Upvision/community-back-end#3]
Following meta data is currently required.

- [] Year (Current active year, to be dynamically calculated. Inclusive of Alumni)
- [] Tenure (Years spent in college, may not be 4/2 years provided year backs)
- [] A list of user editable experiences.

This is what is currently planned, reply to this issue with suggestions.
